/*
 * account_proc.c: implementation of the remote procedures getbalance, deposit and withdraw
 */
#include <stdio.h>
 #include <string.h>
#include "account.h"        /* msg.h generated by rpcgen */

double *
getbalance_1_svc(void *pVoid, struct svc_req *req) {
  static double balance;      /* must be static! */
 
  printf("getbalance_1()\n");
  balance = 1448.0;
  return (&balance);
}

double *
deposit_1_svc(double *amount, struct svc_req *req) {
  static double balance;      /* must be static! */
  
  balance = 1448.0; // TODO: get actual balance
  printf("deposit_1(), amount = %f\n", *amount);
  balance += *amount;
  return (&balance);
}

double *
withdraw_1_svc(amount, req)
  double *amount;
  struct svc_req *req;    /* details of call */
{
  static double balance;      /* must be static! */
  
  balance = 1448.0; // TODO: get actual balance
  printf("withdraw_1(), amount = %f\n", *amount);
  if (balance > *amount) {
    balance -= *amount;
  } else {
    return &balance;
  }
  return (&balance);
}
